### ISSUE TITLE
SPM: Fetching time problem

### ISSUE THREAD

**Issue by Black-Opium** [refiner-io/mobile-sdk-ios#13]
![Снимок экрана 2024-07-22 в 02 34 20](https://github.com/user-attachments/assets/35c281ae-e2e2-48f7-9252-25fbfaf3e1dd)
![Снимок экрана 2024-07-22 в 02 34 49](https://github.com/user-attachments/assets/fbe31867-8cc1-4199-8128-d924db21e391)

**Comment by Black-Opium** [comment]
skipping cache due to an error: https://github.com/refiner-io/mobile-sdk-ios.git: The repository could not be found. Make sure a valid repository exists at the specified location and try again.

**Comment by Black-Opium** [comment]
@tekinalper Already for more than 2 days this problem has been bothering me. At first, I also thought it might be the proxy, VPN, or a bad connection, but the problem is only with RefinerSDK. I also tried loading through VPN - it didn’t help. We have more than 10 libraries in our project, and none of them take this long to load. If the problem wasn’t with a specific library, I wouldn’t have written here.

**Comment by Black-Opium** [comment]
@tekinalper 
Xcode project version 15.0
Xcode version 15.4 (15F31d)
Swift 5

Using the cmd + k, manually clearing the DerivedData folder, using the DevCleaner app, and reset package caches… None of these methods help. The RefinerSDK still takes more than 1 minute to load

**Comment by tekinalper** [comment]
@Black-Opium Looks really odd :/ Googled and found out some people also had the same problem. I wish I could help but unfortunately it's totally out of my control. 

1. Is there any difference between the latest Refiner SDK version 1.4.0 and previous versions?
2. Can you try to upgrade Refiner SDK version in our example project? Maybe somehow caching works?
3. In case of a network problem, can you try to connect mobile data or another network instead of VPN?

**Comment by Black-Opium** [comment]
@tekinalper I tried everything you suggested, but unfortunately nothing worked, not even restarting my Mac… lol.
I tried downloading the previous version and the latest one, but nothing changed.
The package downloads, but very slowly.

**Comment by tekinalper** [comment]
haha did you try using another Mac? 🫠

**Comment by Black-Opium** [comment]
@tekinalper I tried to clone your repository on my Mac. The download speed was terribly slow. However, when I tried to clone it using the command git clone --depth 1 https://github.com/refiner-io/mobile-sdk-ios.git, the repository downloaded surprisingly quickly.

**Comment by Black-Opium** [comment]
I also asked some of my colleagues to download it, but unfortunately, they didn’t experience any issues.

**Comment by Black-Opium** [comment]
I guess I’m not destined to port your SDK to SPM.

**Comment by tekinalper** [comment]
Closing the issue due to no reason found.
