### ISSUE TITLE
Error when compiling to Xcode 15, "__swift_FORCE_LOAD_$_swiftXPC_$_RefinerSDK in RefinerSDK[arm64][3](StartKMM.o)"

### ISSUE THREAD

**Issue by jacssa** [refiner-io/mobile-sdk-ios#14]
**How ​​it's set up:**
RefinerSDK 1.4.0
Xcode 15.0
Cocoapods and or SPM,

**What I'm trying to do:**
Run the build

**What happens:**
Get the error
```
ld: Undefined symbols:
  __swift_FORCE_LOAD_$_swiftXPC, referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_RefinerSDK in RefinerSDK[arm64][3](StartKMM.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
**What I did:**
I tried with Xcode 15.4, and it seems to be working fine with cocoapods, but we're using Xcode 15 for our CI machines, so it needs to work with 15.0.

Also, I tried adding architecture exclude to arm64 for iOS simulator, although it doesn't compile, giving the same error.

**Comment by tekinalper** [comment]
@jacssa It seems likely that you'll need to upgrade the CI machine's version. Xcode users on the web or GitHub issues have reported resolving the "Undefined symbols: __swift_FORCE_LOAD_$_swiftXPC" issue by upgrading.

**Comment by tekinalper** [comment]
Closing this as Xcode upgrade fixes the issue.
