### ISSUE TITLE
Asset validation failed (90208) Invalid Bundle. The bundle app/Frameworks/RefinerSD K.framework does not support the minimum OS Version specified in the Info.plist.

### ISSUE THREAD

**Issue by Black-Opium** [refiner-io/mobile-sdk-ios#3]
Hello. I get an error when submitting/validating a project for App Store Connect (TestFlight). The project is normally assembled and installed in the Simulator, iPhone, there are no problems with it. I repeat, only when I upload the project to AppStoreConnect. I also tried to clear the project cache, the SPM cache, remove the dependency and reinstall. I also cleaned the "DerivedData" folder. None of this helps. When I removed Refiner from the project, my project was validated for AppStoreConnect

"Asset validation failed (90208) Invalid Bundle. The bundle app/Frameworks/RefinerSD K.framework does not support the minimum OS Version specified in the Info.plist."

Refiner 1.3.4

Xcode version 15.3
Project version of Xcode 15
The minimum version of iOS is 15
To download, use SPM

**Comment by yusufonderd** [comment]
Same issue in Xcode 15.3 🚨

**Comment by tekinalper** [comment]
@Black-Opium @yusufonderd Thank you for letting us know the issue. We'll check and get back to you asap.

**Comment by tekinalper** [comment]
The issue looks like related with App Store Connect while using Xcode 15.3 as mentioned here: https://github.com/googleads/swift-package-manager-google-mobile-ads/issues/62 and currently it's common error for other frameworks as well. 

As a quick workaround solution for not being blocked until we cover the issue for Xcode 15.3, we recommend you check out these 2 options;

1. Use Xcode 15.2 temporarily
2. Use Xcode 15.3 and follow the steps mentioned here: https://github.com/googleads/swift-package-manager-google-mobile-ads/issues/62#issuecomment-1988517956

**Comment by tekinalper** [comment]
Fixed in release 1.3.11
