### ISSUE TITLE
1.3.7 version broke SPM installation

### ISSUE THREAD

**Issue by DmtrPonomarenko** [refiner-io/mobile-sdk-ios#5]
Invalid manifest (compiled with: ["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc", "-vfsoverlay", "/var/folders/25/ppgntdwx03b5fdnd1jh0m60r0000gn/T/TemporaryDirectory.gip3sP/vfs.yaml", "-L", "/Applications/Xcode.app/Contents/SharedFrameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Applications/Xcode.app/Contents/SharedFrameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-target", "arm64-apple-macos13.0", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk", "-swift-version", "5", "-I", "/Applications/Xcode.app/Contents/SharedFrameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk", "-package-description-version", "5.5.0", "-Xfrontend", "-serialize-diagnostics-path", "-Xfrontend", "/Users/.../Library/Caches/org.swift.swiftpm/manifests/ManifestLoading/mobile-sdk-ios.dia", "/Package.swift", "-disallow-use-new-driver", "-o", "/var/folders/25/ppgntdwx03b5fdnd1jh0m60r0000gn/T/TemporaryDirectory.2BXpQR/mobile-sdk-ios-manifest"])

**Comment by tekinalper** [comment]
Hi, thank you for reaching out. We're working to fix it asap.

**Comment by tekinalper** [comment]
@DmtrPonomarenko It's fixed with the release of the version 1.3.9
