### ISSUE TITLE
Unsupported iOS version 

### ISSUE THREAD

**Issue by Black-Opium** [refiner-io/mobile-sdk-ios#8]
I can't send the build to App Store Connect and TestFlight due to an error in the library.
MyProject **minimal iOS version is 15**
SPM

> Error uploading ipa file: 
> [Application Loader Error Output]:
> ERROR: [ContentDelivery.Uploader] Asset validation failed (90208) Invalid Bundle. The bundle Test/Frameworks/RefinerSDK.framework does not support the minimum OS Version specified in the Info.plist.
>  
> [Application Loader Error Output]: 
> Error uploading '/var/folders/bv/tvd8h0vx2g57s9dtwh4wsrwh0000gn/T/e6885e8f-bb84-4270-b5d8-a86c142c8664.ipa'.
> 
> [Application Loader Error Output]:
> Asset validation failed Invalid Bundle. The bundle Test/Frameworks/RefinerSDK.framework does not support the minimum OS Version specified in the Info.plist. (90208)
> 
> [Application Loader Error Output]:
> The call to the altool completed with a non-zero exit status: 1. This indicates a failure.

**Comment by tekinalper** [comment]
@Black-Opium is it possible to temporarily use pod instead of SPM? I guess Apple didn't find a solution to this on their end. I'll try to patch the workaround for SPM in our next release.

**Comment by tekinalper** [comment]
Fixed in release 1.3.11
