### ISSUE TITLE
Framework CoreAudioTypes not found

### ISSUE THREAD

**Issue by wow-such-amazing** [refiner-io/mobile-sdk-ios#9]
Hey folks! 

I've updated Refiner from `1.2.0` to `1.3.9` and I now have this error when trying to build the project. Do you have an idea why that could happen and maybe any tips on what I could do to fix it? 

I suspect maybe some of our Xcode Project settings, but can't really figure out 🤔 

<img width="760" alt="Screenshot 2024-06-05 at 14 01 05" src="https://github.com/refiner-io/mobile-sdk-ios/assets/7022709/09ebd60d-9fe8-4e64-9f1c-3b87cc51f510">

Cheers!

**Comment by tekinalper** [comment]
Hi @wow-such-amazing! What is your Xcode version? Might be related to that.

**Comment by wow-such-amazing** [comment]
Hey @tekinalper, we use 15.2. I had a thought about that. Let me try 15.4 👍

**Comment by wow-such-amazing** [comment]
Looks like upgrading xcode fixed the issue for Refiner, but now we have the issue for Sentry 😅 

https://github.com/getsentry/sentry-cocoa/issues/3980

I'm gonna check if using xcode 15.2 and refiner 1.3.0 does the trick for our requirements 👍

**Comment by wow-such-amazing** [comment]
Now that I've been able to make everything compile it fails to get delivered to the store 😁 Let me know if anything comes to mind, I'll keep you posted about my adventures 😄 

```
[Application Loader Error Output]: Asset validation failed CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'RefinerInternalSDK' under the iOS application 'Swapcard.app'.
[Application Loader Error Output]: Asset validation failed Invalid Bundle. The bundle at 'Swapcard.app/Frameworks/RefinerSDK.framework' contains disallowed nested bundles.
[Application Loader Error Output]: Asset validation failed Invalid Bundle. The bundle at 'Swapcard.app/Frameworks/RefinerSDK.framework' contains disallowed file 'Frameworks'.
```

**Comment by wow-such-amazing** [comment]
I've fixed the problem by using cocoapods instead of SPM. Now things build fine 😄 Thanks for bearing with me, maybe this thread could be interesting to someone 👀

**Comment by tekinalper** [comment]
No worries! 😅 Great to hear it works and not blocks you. I'll let you know if we find something related to the error you got.
